apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: $SERVICE_NAME
          image: gcr.io/${GCP_PROJECT_ID}/${BRANCH_NAME}/${SERVICE_NAME}
          imagePullPolicy: Always